import React, { useMemo } from "react";
import { AbsoluteFill, useVideoConfig, useCurrentFrame, interpolate } from "remotion";

interface CaptionCue {
    startFrame: number;
    endFrame: number;
    text: string;
}

interface CaptionsProps {
    srtContent: string;
    style: string;
}

/** Parses SRT timestamp to seconds */
const parseTimestamp = (timestamp: string): number => {
    const [hms, ms] = timestamp.split(",");
    const [h, m, s] = hms.split(":").map(Number);
    return h * 3600 + m * 60 + s + Number(ms) / 1000;
};

export const Captions: React.FC<CaptionsProps> = ({ srtContent, style }) => {
    const frame = useCurrentFrame();
    const { fps } = useVideoConfig();

    const cues = useMemo(() => {
        if (!srtContent) return [];

        const blocks = srtContent.trim().split(/\n\s*\n/);
        return blocks.map((block) => {
            const lines = block.split("\n");
            const timeLine = lines[1];
            const text = lines.slice(2).join(" ");

            const [start, end] = timeLine.split(" --> ");

            return {
                startFrame: Math.floor(parseTimestamp(start) * fps),
                endFrame: Math.floor(parseTimestamp(end) * fps),
                text: text.trim(),
            };
        });
    }, [srtContent, fps]);

    const activeCue = cues.find(c => frame >= c.startFrame && frame < c.endFrame);

    if (!activeCue) return null;

    // Split text into 2-3 words chunks (approximate per user request)
    // Actually, SRT generated by Deepgram usually already has small enough chunks,
    // but we'll ensure they don't look too crowded.

    const renderStyledText = (text: string) => {
        switch (style) {
            case "karaoke":
                return (
                    <span className="text-white drop-shadow-[0_4px_4px_rgba(0,0,0,0.5)] bg-black/40 px-6 py-2 rounded-xl">
                        {text.split(" ").map((word, i) => (
                            <span key={i} className={i % 2 === 0 ? "text-yellow-400" : "text-white"}>
                                {word}{" "}
                            </span>
                        ))}
                    </span>
                );
            case "popup":
                const scale = interpolate(frame, [activeCue.startFrame, activeCue.startFrame + 5], [0.8, 1], { extrapolateRight: "clamp" });
                return (
                    <span style={{ transform: `scale(${scale})` }} className="text-white font-black italic uppercase text-6xl drop-shadow-[0_8px_0_rgba(0,0,0,1)]">
                        {text}
                    </span>
                );
            case "glow":
                return (
                    <span className="text-indigo-200 text-5xl font-bold drop-shadow-[0_0_15px_rgba(99,102,241,0.8)]">
                        {text}
                    </span>
                );
            case "gradient":
                return (
                    <span className="text-white text-5xl font-black bg-gradient-to-r from-indigo-500 via-purple-500 to-rose-500 bg-clip-text text-transparent">
                        {text}
                    </span>
                );
            case "typewriter":
                return (
                    <span className="text-white font-mono text-4xl bg-black px-4 py-2 border-r-4 border-rose-500">
                        {text}
                    </span>
                );
            default: // classic
                return (
                    <span className="text-white font-extrabold text-5xl uppercase text-center px-8 drop-shadow-[0_4px_10px_rgba(0,0,0,1)]">
                        {text}
                    </span>
                );
        }
    };

    return (
        <AbsoluteFill className="flex items-center justify-center p-20 text-center pointer-events-none" style={{ top: "35%" }}>
            <div className="max-w-[80%] flex flex-wrap justify-center items-center">
                {renderStyledText(activeCue.text)}
            </div>
        </AbsoluteFill>
    );
};
